wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.13
    start_time: 1701375608.663893
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.13.5
      8:
      - 5
epochs:
  desc: null
  value: 10
geometry:
  desc: null
  value: euclidean
method:
  desc: null
  value: bezier
n:
  desc: null
  value: 100
nc:
  desc: null
  value: 10
regularization:
  desc: null
  value: 1.0e-05
